//! `sysenv short` — install shell shims for every subcommand so it can be
//! invoked from anywhere with a short name:
//!   spath = sysenv path, senv = sysenv env, slink = sysenv link,
//!   shttp = sysenv http, sai = sysenv ai

use crate::link;
use crate::store::common;
use crate::store::Scope;
use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

/// (short name, subcommand)
pub const SHIMS: &[(&str, &str)] = &[
    ("spath", "path"),
    ("senv", "env"),
    ("slink", "link"),
    ("shttp", "http"),
    ("sai", "ai"),
];

fn shim_filename(name: &str) -> String {
    #[cfg(windows)]
    {
        format!("{name}.cmd")
    }
    #[cfg(not(windows))]
    {
        name.to_string()
    }
}

fn shim_content(exe: &Path, sub: &str) -> String {
    #[cfg(windows)]
    {
        format!("@echo off\r\n\"{}\" {sub} %*\r\n", exe.display())
    }
    #[cfg(not(windows))]
    {
        format!("#!/bin/sh\n# Generated by sysenv. Do not edit.\nexec \"{}\" {sub} \"$@\"\n", exe.display())
    }
}

/// Install the shims into `dir` (default: the managed bin directory) and make
/// sure that directory is on the PATH unless `temporary`.
pub fn cmd_short(dir: Option<PathBuf>, force: bool, temporary: bool) -> Result<()> {
    let bin_dir = match dir {
        Some(d) => d,
        None => link::default_bin_dir()?,
    };
    std::fs::create_dir_all(&bin_dir)
        .with_context(|| format!("cannot create directory {}", bin_dir.display()))?;

    let exe = std::env::current_exe().context("cannot locate the sysenv binary")?;

    let mut created: Vec<PathBuf> = Vec::new();
    for (name, sub) in SHIMS {
        let path = bin_dir.join(shim_filename(name));
        if path.exists() && !force {
            bail!("{} already exists (use --force to overwrite)", path.display());
        }
        std::fs::write(&path, shim_content(&exe, sub))
            .with_context(|| format!("cannot write {}", path.display()))?;
        #[cfg(not(windows))]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perm = std::fs::metadata(&path)
                .with_context(|| format!("cannot stat {}", path.display()))?
                .permissions();
            perm.set_mode(0o755);
            std::fs::set_permissions(&path, perm).with_context(|| format!("cannot chmod {}", path.display()))?;
        }
        created.push(path);
    }

    // Make sure the shim directory is on the PATH (unless --temporary).
    let bin_abs = common::absolutize_dir(&bin_dir.to_string_lossy())?;
    let on_path = crate::store::current_path_entries()
        .iter()
        .any(|e| common::path_eq(e, &bin_abs));
    if !on_path {
        if temporary {
            println!(
                "[temporary] {} is not on PATH yet; add it with:\n  {}",
                bin_abs,
                common::shell_export_snippet(
                    "PATH",
                    &common::join_path(&common::merge_entries(
                        &crate::store::current_path_entries(),
                        &[bin_abs.clone()]
                    ))
                )
            );
        } else {
            crate::path::cmd_add(&bin_abs, Scope::User, false, false)?;
        }
    }

    println!("Created {} shortcut(s) in {}:", created.len(), bin_dir.display());
    for p in &created {
        println!("  {}", p.display());
    }
    println!("Now available as: {}", SHIMS.iter().map(|(n, _)| *n).collect::<Vec<_>>().join(", "));
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_names_and_targets() {
        assert_eq!(SHIMS.len(), 5);
        let subs: Vec<&str> = SHIMS.iter().map(|(_, s)| *s).collect();
        assert_eq!(subs, vec!["path", "env", "link", "http", "ai"]);
        let names: Vec<&str> = SHIMS.iter().map(|(n, _)| *n).collect();
        assert_eq!(names, vec!["spath", "senv", "slink", "shttp", "sai"]);
    }

    #[cfg(windows)]
    #[test]
    fn windows_shim_content() {
        let c = shim_content(Path::new(r"C:\tools\sysenv.exe"), "path");
        assert!(c.starts_with("@echo off\r\n"));
        assert!(c.contains(r#""C:\tools\sysenv.exe" path %*"#));
    }

    #[cfg(not(windows))]
    #[test]
    fn unix_shim_content() {
        let c = shim_content(Path::new("/opt/sysenv"), "env");
        assert!(c.starts_with("#!/bin/sh\n"));
        assert!(c.contains(r#"exec "/opt/sysenv" env "$@""#));
    }
}
